apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserve
  labels:
    app: goserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goserve
  template:
    metadata:
      labels:
        app: goserve
    spec:
      containers:
      - name: goserve
        image: quay.io/vqcomms/goserve:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        env:
          - name: CONFIGMAP_NAME
            value: my-config